presets = ["highfive", "rfcbot", "bors", "appveyor"]

[[hooks]]
url = "https://www.ncameron.org/triage/hook"
content-type = "json"
require-secret = false
events = ["issues", "issue_comment"]

[[hooks]]
url = "https://rust-logs-bot.timnn.me"
content-type = "json"
require-secret = false
events = ["check_run", "issue_comment", "status"]

[[hooks]]
url = "https://perf.rust-lang.org/perf/github-hook"
content-type = "json"
require-secret = true
events = ["issue_comment", "pull_request", "status"]

[[hooks]]
url = "https://crater.rust-lang.org/webhooks"
content-type = "json"
require-secret = true
events = ["issue_comment"]
